export const MALE_GENDER_INCREMENETER = 66.47;
export const FEMALE_GENDER_INCREMENETER = 655.1;

export const MALE_WEIGHT_MULTIPLIER = 13.75;
export const FEMALE_WEIGHT_MULTIPLIER = 9.563;

export const MALE_LENGTH_MULTIPLIER = 5.003;
export const FEMALE_LENGTH_MULTIPLIER = 1.85;

export const MALE_AGE_MULTIPLIER = 6.755;
export const FEMALE_AGE_MULTIPLIER = 4.676;
